### ISSUE TITLE
Cannot delete backup files

### ISSUE THREAD

**Issue by tringuyenduc2903** [Laravel-Backpack/BackupManager#126]
# Bug report

### What I did:

Delete 1 backup file

### What I expected to happen:

Deleted successfully

### What happened:

An exception occurred: **Non-static method Illuminate\Http\Request::input() cannot be called statically {"userId":1,"exception":"[object] (Error(code: 0): Non-static method Illuminate\\Http\\Request::input() cannot be called statically at /var/www/html/vendor/backpack/backupmanager/src/app/Http/Controllers/BackupController.php:118)**
https://github.com/Laravel-Backpack/BackupManager/commit/567f12068424cf173eb21aeaef061477de394157

### What I've already tried to fix it:

The error is in the most recent fix
https://github.com/Laravel-Backpack/BackupManager/commit/567f12068424cf173eb21aeaef061477de394157

### Backpack, Laravel, PHP, DB version:

![image](https://github.com/Laravel-Backpack/BackupManager/assets/101564593/0bd66043-2058-4ac2-9ba8-4ba1092239b4)

**Comment by tringuyenduc2903** [comment]
The Download feature also has the same error. It's sad because you created a problem when you fixed a problem.

**Comment by pxpm** [comment]
Hey @tringuyenduc2903 so sorry. I swear this time was not on purpose. 

My static analysis plugin can't use the Request Facade for some reason. I've just tested again in the previous version, and when I save the file it automatically converts the Facades to full namespace imports, but always import the implementation of the Request instead of the Facade. Weird.

Didn't noticed it, sorry again for that. Already tagged 5.0.2 with the Facade back in. 

Cheers
