### ISSUE TITLE
Deleting backup error "The backup file has NOT been deleted." [404 Not Found]

### ISSUE THREAD

**Issue by RamiMustaklem** [Laravel-Backpack/BackupManager#16]

**Comment by tabacitu** [comment]
Hi @RamiMustaklem ,

Please take a look at the AJAX request for more information. If you're on the local environment, you should be able to see the request and its response in your browser's developer tools. The response most likely has the error, so we can figure out what's happening.

Cheers!

**Comment by vincenzoraco** [comment]
I got this error too. Unfortunately I can't see if it's Backpack Controller or Spatie/Laravel-backup package mistake - but basically, the error is:

* I tested the app on a dev server only

`Route::delete('backup/delete/{file_name?}', 'BackupController@delete');`

The URL to delete will be this:

`http://www.laravel.dev/admin/backup/delete/http---localhost/2016-12-12-025620.zip?disk=backups` - where `http---localhost/2016-12-12-025620.zip` is the file name which goes in conflict with the route parameter `{file_name?}` since there is a `/` in the middle of the file_name.

The temporary solution is `Route::delete('backup/delete/{file_name?}', 'BackupController@delete')->where('file_name', '(.*)');`

The problem is that shouldn't be `http---localhost/` since it's irrelevant.

* the file is in `vendor/backpack/backupmanager/src/app/Http/routes.php`.
