### ISSUE TITLE
Backup Not Function

### ISSUE THREAD

**Issue by imansugirman** [Laravel-Backpack/BackupManager#53]
Backups not functions after click Create New a Backup buttons.  just reload and blank result 
![jepretan layar 2018-05-31 pada 23 40 35](https://user-images.githubusercontent.com/38036171/40795365-0c24239a-652c-11e8-922a-46dce28b03bd.png)

### Backpack, Laravel, PHP, DB version:
PHP : 7.2
Mysql : 5.7.21
Laravel : 5.6
```
"backpack/backupmanager": "^1.4"
"backpack/crud": "^3.4",
"backpack/permissionmanager": "^2.1",
```

**Comment by tabacitu** [comment]
@imansugirman just checked and it works for me. 

This packge is just an interface for https://github.com/spatie/laravel-backup - so please check that you've correctly configured that package, and ```php artisan backup:run``` works for you. Otherwise this package won't either.

Let me know if it hasn't been a misconfiguration, or some bug introduced by spatie/laravel-backup and I'll happily reopen the issue.

Cheers!
