### ISSUE TITLE
Backup failed because The dump process failed with exitcode 1 : General error : The system cannot find the path specified.

### ISSUE THREAD

**Issue by jusyjk** [Laravel-Backpack/BackupManager#57]
# Bug report

**Comment by tabacitu** [comment]
Hi @jusyjk - it sounds to me like you're using the old configuration file, ```config/laravel-backup.php``` instead of the new one (```config/backup.php```).

I recommend you delete that the ```config/laravel-backup.php``` file and re-publish the new file using:

```
php artisan vendor:publish --provider="Backpack\BackupManager\BackupManagerServiceProvider"  --tag=config
```

Hope it helps.
Cheers!

**Comment by tabacitu** [comment]
PS. This new file sends emails on backup errors, so make sure your mail is properly configured too, in your .ENV file. Even on localhost, using mailtrap or something.

**Comment by jusyjk** [comment]
it shows no error but i'm geting any backup file 
once i click backup it shows page will be refreshed in 3 sec
but after that in public there is no backup file
Can u help me out?
Tnx

**Comment by tabacitu** [comment]
Hi @jusyjk ,

This package is just a simple interface for [spatie/laravel-backup](https://github.com/spatie/laravel-backup). I suspect your problem is not that _this_ package is not working, but _laravel-backup_ is not working.

To make sure it's working, I recommend you run ```php artisan backup:run``` in the command line. There you'll be able to see the entire stack trace, and see what went wrong. Also, their issues on Github provide solutions for the most frequent problems - this might be one of them.

Hope it helps.
Cheers!
