### ISSUE TITLE
not work in lumen 5.2+

### ISSUE THREAD

**Issue by maojindao55** [Laravel-Backpack/BackupManager#8]
in bootstrap/app.php ，i add :      
```
$app->register(Spatie\Backup\BackupServiceProvider::class);
$app->register(Backpack\BackupManager\BackupManagerServiceProvider::class);
```   
BUT it came the error:
```                                                                                                               
  [Illuminate\Contracts\Container\BindingResolutionException]                                                           
  Target [Illuminate\Contracts\Logging\Log] is not instantiable while
 building [Spatie\Backup\Notifications\Notifier]. 
```

**Comment by tabacitu** [comment]
Hi @maojindao55 ,

I've never tried using Backpack with Lumen, but it _should_ work after installing all requirements, since it's basically a stripped-down version of Laravel. 

1) Have you tried [this suggestion from Spatie/Backup](https://github.com/spatie/laravel-backup/issues/72#issuecomment-196332163)?
2) Do the other Backpack packages work for you on Lumen?

Cheers!
