### ISSUE TITLE
The GET method is not supported for this route. Supported methods: PUT

### ISSUE THREAD

**Issue by vahidtakro** [Laravel-Backpack/BackupManager#93]
# Bug report

**Comment by vahidtakro** [comment]
I receive this error when I click on "create a new backup" and "delete" of the backup I created through php artisan backup:run .
how can I fix that? thanks.

**Comment by tabacitu** [comment]
@vahidtakro it's possible that your server software turns PUT requests into GET. As you can see here this addon uses a PUT route: https://github.com/Laravel-Backpack/BackupManager/issues/93

You can overwrite the routes by copy-pasting this file into your `routes/backpack/backupmanager.php`. Then the addon will pick up YOUR file instead of ITS file.

Hope it helps.
