### ISSUE TITLE
artisan call

### ISSUE THREAD

**Issue by mohanad69** [Laravel-Backpack/BackupManager#95]
**when adding artisan command in route it did not create my backup**

```
Route::get('test', function () {

    \Artisan::call('backup:run', ['--only-db' =>true, '--disable-notifications' => true]);

    dd("Cache is cleared");

});
```

**Comment by tabacitu** [comment]
Hey @mohanad69 ,

That command is actually provided by [spatie/laravel-backup](https://github.com/spatie/laravel-backup), not this package. I recommend you start debugging by looking to their issues & PRs - could be a bug there (unlikely since the package is heavily unit-tested), or possibly a server misconfiguration on your end.

Sorry I can't be of more help.
Cheers!
