### ISSUE TITLE
No user feedback after clicking button to create a backup

### ISSUE THREAD

**Issue by malle-pietje** [Laravel-Backpack/BackupManager#96]
# Bug report

### What I did:
I clicked on the "Create a new backup" button.

### What I expected to happen:
Some form of feedback (spinner) showing something is happening as I see on the screenshot in the main README.

### What happened:
Nothing happens until a toaster message shows the backup was created.

### What I've already tried to fix it:
Nothing I can see I can do about this.

### Backpack, Laravel, PHP, DB version:

```bash
$ php artisan backpack:version
### PHP VERSION:
PHP 7.4.9 (cli) (built: Jul  5 2021 13:33:00) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.69.0@545181da688db64fed6d8427e55f630a90ca0d32

### BACKPACK VERSION:
4.1.60@bec5cfa11f0cd0712c79256748acf5850080c0ee
```

**Comment by tabacitu** [comment]
Hey @malle-pietje ,

I agree, there should be some form of feedback to let the user know there's work in progress. **Will do.** There used to be a spinner there in Backpack v3 (using ladda buttons) but since v4 that's no longer included in Backpack, so no spinner any more.

But please note that we're currently hard at work trying to launch Backpack 4.2, so we're probably not going to have time to do this in the immediate future. But I agree it needs to be done, and we'll take a stab at it soon enough.

Cheers!

**Comment by malle-pietje** [comment]
@tabacitu thanks. For the time being I’ll try to implement a quick fix using jQuery.

**Comment by tabacitu** [comment]
@malle-pietje happy to tell you we're finally fixing this UX problem in https://github.com/Laravel-Backpack/BackupManager/pull/103 🎉🎉🎉
